<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <AssemblyName>OmniSharp</AssemblyName>
        <OutputType>Exe</OutputType>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <RollForward>LatestMajor</RollForward>
        <SkipHostDlls>true</SkipHostDlls>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\OmniSharp.Stdio\OmniSharp.Stdio.csproj" />
    </ItemGroup>

</Project>
